name: '[Re-usable workflow] build app'
on:
  workflow_call:
    inputs:
      project_names:
        description: 'Project name(s), comma separated'
        required: true
        type: string

jobs:
  build_app:
    runs-on: ubuntu-latest
    name: 'Build app(s) ğŸ—ï¸'
    steps:
      - name: 'Checkout ğŸ“¥'
        uses: actions/checkout@v4

      - name: 'Install dependencies ğŸ“¦'
        uses: ./.github/actions/install-deps
        with:
          nx-cache-key: 'nx-build-${{ inputs.project_names }}'

      - name: 'Set configuration'
        id: set-configuration
        run: |
          echo "Setting up configuration for build step"
          build_configuration="production"
          branch_name="${{ github.ref }}"
          if [ $branch_name != 'refs/main' ]; then
            build_configuration="staging"
          fi
          echo "$build_configuration is the configuration for branch $branch_name"
          echo "build_configuration=$build_configuration" >> $GITHUB_OUTPUT

      - name: 'Build app(s) ğŸ—ï¸'
        run: |
          echo "running: npx nx run-many -t build --projects=${{ inputs.project_names }} --configuration=${{ steps.set-configuration.outputs.build_configuration }}"
          npx nx run-many -t build --projects=${{ inputs.project_names }} --configuration=${{ steps.set-configuration.outputs.build_configuration }}
        env:
          NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

      - name: 'Upload artifacts ğŸš€'
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app
          path: 'dist'
